# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-22 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20161219_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='point',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, upload_to='blog/post/%Y/%m/%d'),
        ),
    ]
