# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-26 05:33
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20161222_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='point',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator('^[+-]?[\\d\\.]+,[+-]?[\\d\\.]+$')]),
        ),
    ]
